### PR TITLE
Generate a sequence of instructions for divisions on Arm targets

### PR DESCRIPTION
**Pull request by DrXiao**
Division instruction doesn't exist in ARMv7-A  (#46 ), but the current implementation of shecc still generates it to compute the result for division or modulo operations.

Thus, here adjusts arm-codegen so that shecc will generate an instruction sequence to achieve integer division without relying on any division instruction.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
1. Add new command line option `+m`, which indicates the use of hardware integer multiplication and division instructions.
2. Extend `tests/driver.sh` for more integer division coverage.

**Comment by DrXiao** [comment]
@jserv I understand that we can add a `+m` option to determine whether shecc generates hardware integer multiplication and division instructions.

However, I consider shecc can still generate multiplication instructions for ARM even if the `+m` option is closed. Because ARMv7-A inherently includes multiplication instruction, we can generate it directly without any concern.

Therefore, for the implementation of the `+m` option, I think that I can just handle whether the hardware integer division instructions are generated for ARM.

**Comment by DrXiao** [comment]
The reference implementation mentioned in #46 assumes that the dividend and divisor are unsigned integers, but it may fail if at least one of them is a signed integer.

Can I suppose that shecc will not encounter any signed integer division and just handle unsigned integer division?
Or do we must let shecc handle both of them?

**Comment by jserv** [comment]
By the way, I enjoy this article [Fast(est) Double-Word Integer Division](https://skanthak.hier-im-netz.de/integer.html).

**Comment by DrXiao** [comment]
I have a new question about the **right shift operation**. During these days, I test the following code:
```c
/* test.c */
int main() {
    printf("%d\n", -2 >> 31);
    return 0;
}
```
In C99, It mentions that it is an **implementation-defined** behavior for using right shift operation on signed integers.

If we use the gcc and clang to compile and execute it, we can all obtain the output `-1`:
```
$ gcc -o test test.c
$ ./test
-1
$ clang -o test test.c
$ ./test
-1
```
I believe it may be a convention that many compilers use **arithmetic right shift** instructions for signed integers. 

But, when using shecc to test the right shift operation, we will get the output `1` because shecc uses **logical right shift** instructions for signed integers:
```
$ qemu-arm out/shecc-stage2.elf -o test test.c
$ qemu-arm test
1
```

Should we instruct shecc to generate arithmetic right shift instructions as well?

**Comment by jserv** [comment]
> In C99, It mentions that it is an **implementation-defined** behavior for using right shift operation on signed integers.
[...]
> Should we instruct shecc to generate arithmetic right shift instructions as well?

@vacantron, can you comment this?

**Review by jserv — CHANGES_REQUESTED** [review]
Rebase the latest `master` branch and resolve the conflicts.

**Review by jserv — CHANGES_REQUESTED** [review]
Rebase the latest `master` branch for bool specific fixes.

**Comment by jserv** [comment]
Thank @DrXiao for contributing!

**Comment by DrXiao** [comment]
@jserv May I ask why this PR can be merged? Or will this PR be reopened and requested to be improved again in the future?

**Comment by jserv** [comment]
> May I ask why this PR can be merged? Or will this PR be reopened and requested to be improved again in the future?

The latter.

**Pull request merged**
