### PR TITLE
Support octal literals

### PR DESCRIPTION
**Pull request by fennecJ**
As title, this PR basically implement support for octal literals in numeric constants and function parameters.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Read https://cbea.ms/git-commit/ carefully and refine the commits.

**Comment by jserv** [comment]
You should extend the test suite for octal literals.

**Comment by fennecJ** [comment]
I just added some test cases for octal literals, but I found that the current testing method has significant limitations. It seems like it can only test values between 0 and 255. Additionally, testing for negative numbers requires handling through printf. Should we consider improving our testing process to handle a broader range of cases more efficiently? What are your thoughts on this?

**Comment by jserv** [comment]
> I just added some test cases for octal literals, but I found that the current testing method has significant limitations. It seems like it can only test values where the final result is between 0 and 255 (a byte) . Additionally, testing for negative numbers requires handling through printf. Should we consider improving our testing process to handle a broader range of cases more efficiently? What are your thoughts on this?

You can create a new issue to track the improvements of the test suite.

**Review by ChAoSUnItY — APPROVED** [review]

**Comment by jserv** [comment]
Thank @fennecJ for contributing!

**Pull request merged**
